"""RGNR8 web app shell — multi-tenant HTTP surface for the owner dashboard + API."""

from __future__ import annotations

from .apikeys import ApiKey, ApiKeyService, ApiKeyStore, InMemoryApiKeyStore, SqlApiKeyStore
from .app import Request, Response, WebApp
from .audit import AuditEvent, AuditSink, InMemoryAuditLog, SqlAuditLog
from .auth import (
    Authenticator,
    JwtAuthenticator,
    JwtError,
    StaticTokenAuthenticator,
    sign_jwt,
    verify_jwt,
)
from .books_screens import (
    render_books_home,
    render_books_statements,
    render_chart_of_accounts,
    render_register,
)
from .credentials import (
    AuthError,
    AuthService,
    Credential,
    CredentialStore,
    InMemoryCredentialStore,
    InMemoryVerificationTokenStore,
    PasswordHasher,
    SqlCredentialStore,
    SqlVerificationTokenStore,
    TokenPurpose,
    VerificationToken,
    VerificationTokenStore,
)
from .financial_package import (
    FinancialPackageReader,
    PackageIntegrityError,
    canonicalize,
    fingerprint_content,
    render_package_html,
    verify_package,
)
from .invitations import (
    InMemoryInvitationStore,
    Invitation,
    InvitationError,
    InvitationService,
    InvitationStatus,
    InvitationStore,
    SqlInvitationStore,
)
from .jwks import (
    HttpJwksProvider,
    JwksAuthenticator,
    JwksHttpSource,
    JwksProvider,
    StaticJwksProvider,
    UrllibJwksSource,
    jwk_from_public_numbers,
    verify_rs256,
)
from .ledger_client import (
    LedgerClient,
    LedgerResponse,
    LedgerTransport,
    PooledHttpTransport,
    UrllibTransport,
)
from .middleware import (
    ObservedApp,
    RateLimiter,
    counter_request_ids,
    default_rate_limit_key,
    make_rate_limit_key,
    security_headers,
    with_security_headers,
)
from .openapi import API_VERSION, build_openapi
from .owner_reports import (
    render_aging,
    render_budget,
    render_owner_report,
    render_retained_earnings,
)
from .rbac import (
    ROLE_PERMISSIONS,
    AccessPolicy,
    InMemoryUserDirectory,
    Membership,
    Permission,
    Role,
    SqlUserDirectory,
    User,
    UserDirectory,
    role_permissions,
)
from .screens import (
    CloseBoard,
    CloseTask,
    default_close_board,
    render_ar_body,
    render_briefing_body,
    render_cash_body,
    render_close_body,
    render_connect_page,
    render_packages_body,
    render_reports_list,
    render_scenario_body,
)
from .server import make_handler, serve
from .shell import (
    render_app_home,
    render_audit_log,
    render_login_html,
    render_shell,
    render_users_admin,
)
from .sql_store import SqlTenantStore
from .store import (
    InMemoryTenantStore,
    JsonFileTenantStore,
    TenantDef,
    TenantState,
    TenantStore,
)
from .transactions import DEFAULT_CATEGORIES, BankTransaction, render_transactions, summarize
from .webhook_outbox import (
    DEAD,
    DELIVERED,
    PENDING,
    DeliverySummary,
    DurableWebhookDispatcher,
    InMemoryWebhookOutbox,
    OutboxDelivery,
    SqlWebhookOutbox,
    WebhookOutbox,
    backoff_seconds,
)
from .webhooks_out import (
    DeliveryResult,
    InMemoryWebhookEndpointStore,
    PlatformEvent,
    SqlWebhookEndpointStore,
    UrllibHttpClient,
    WebhookDispatcher,
    WebhookEndpoint,
    WebhookEndpointStore,
    briefing_sent_event,
    cash_at_risk_event,
    close_sealed_event,
    validate_target,
)
from .webhooks_out import (
    HttpResponse as WebhookHttpResponse,
)
from .webhooks_out import (
    sign as sign_webhook,
)
from .wsgi import request_from_environ, wsgi_app

__version__ = "0.1.0"

__all__ = [
    "WebApp",
    "Request",
    "Response",
    "serve",
    "make_handler",
    "wsgi_app",
    "request_from_environ",
    "RateLimiter",
    "ObservedApp",
    "security_headers",
    "with_security_headers",
    "default_rate_limit_key",
    "make_rate_limit_key",
    "counter_request_ids",
    "render_login_html",
    "render_shell",
    "render_app_home",
    "render_users_admin",
    "render_audit_log",
    "render_transactions",
    "BankTransaction",
    "DEFAULT_CATEGORIES",
    "summarize",
    "render_cash_body",
    "render_briefing_body",
    "render_close_body",
    "render_packages_body",
    "render_reports_list",
    "render_connect_page",
    "render_scenario_body",
    "render_ar_body",
    "CloseBoard",
    "CloseTask",
    "default_close_board",
    "TenantStore",
    "InMemoryTenantStore",
    "JsonFileTenantStore",
    "SqlTenantStore",
    "TenantState",
    "TenantDef",
    "FinancialPackageReader",
    "PackageIntegrityError",
    "canonicalize",
    "fingerprint_content",
    "verify_package",
    "render_package_html",
    "Authenticator",
    "StaticTokenAuthenticator",
    "JwtAuthenticator",
    "JwtError",
    "sign_jwt",
    "verify_jwt",
    "JwksAuthenticator",
    "JwksProvider",
    "StaticJwksProvider",
    "HttpJwksProvider",
    "JwksHttpSource",
    "UrllibJwksSource",
    "verify_rs256",
    "jwk_from_public_numbers",
    "AccessPolicy",
    "UserDirectory",
    "InMemoryUserDirectory",
    "SqlUserDirectory",
    "User",
    "Membership",
    "Role",
    "Permission",
    "ROLE_PERMISSIONS",
    "role_permissions",
    "AuditEvent",
    "AuditSink",
    "InMemoryAuditLog",
    "SqlAuditLog",
    "Invitation",
    "InvitationService",
    "InvitationStatus",
    "InvitationStore",
    "InMemoryInvitationStore",
    "InvitationError",
    "AuthError",
    "AuthService",
    "Credential",
    "CredentialStore",
    "InMemoryCredentialStore",
    "InMemoryVerificationTokenStore",
    "PasswordHasher",
    "SqlCredentialStore",
    "SqlVerificationTokenStore",
    "TokenPurpose",
    "VerificationToken",
    "VerificationTokenStore",
    "ApiKey",
    "ApiKeyService",
    "ApiKeyStore",
    "InMemoryApiKeyStore",
    "SqlApiKeyStore",
    "SqlInvitationStore",
    "build_openapi",
    "LedgerClient",
    "LedgerResponse",
    "LedgerTransport",
    "PooledHttpTransport",
    "UrllibTransport",
    "render_books_home",
    "render_books_statements",
    "render_chart_of_accounts",
    "render_register",
    "render_owner_report",
    "render_aging",
    "render_budget",
    "render_retained_earnings",
    "API_VERSION",
    "WebhookEndpoint",
    "WebhookEndpointStore",
    "InMemoryWebhookEndpointStore",
    "SqlWebhookEndpointStore",
    "UrllibHttpClient",
    "WebhookHttpResponse",
    "WebhookDispatcher",
    "DurableWebhookDispatcher",
    "WebhookOutbox",
    "InMemoryWebhookOutbox",
    "SqlWebhookOutbox",
    "OutboxDelivery",
    "DeliverySummary",
    "backoff_seconds",
    "PENDING",
    "DELIVERED",
    "DEAD",
    "PlatformEvent",
    "DeliveryResult",
    "sign_webhook",
    "cash_at_risk_event",
    "close_sealed_event",
    "briefing_sent_event",
    "validate_target",
]
