"""RGNR8 web app shell — multi-tenant HTTP surface for the owner dashboard + API."""

from __future__ import annotations

from .app import Request, Response, WebApp
from .server import make_handler, serve
from .wsgi import request_from_environ, wsgi_app
from .middleware import (
    ObservedApp,
    RateLimiter,
    counter_request_ids,
    default_rate_limit_key,
    security_headers,
    with_security_headers,
)
from .shell import render_app_home, render_login_html, render_shell, render_users_admin
from .transactions import BankTransaction, DEFAULT_CATEGORIES, render_transactions, summarize
from .screens import (
    CloseBoard,
    CloseTask,
    default_close_board,
    render_briefing_body,
    render_cash_body,
    render_close_body,
    render_packages_body,
)
from .store import (
    InMemoryTenantStore,
    JsonFileTenantStore,
    TenantDef,
    TenantState,
    TenantStore,
)
from .sql_store import SqlTenantStore
from .financial_package import (
    FinancialPackageReader,
    PackageIntegrityError,
    canonicalize,
    fingerprint_content,
    render_package_html,
    verify_package,
)
from .auth import (
    Authenticator,
    JwtAuthenticator,
    JwtError,
    StaticTokenAuthenticator,
    sign_jwt,
    verify_jwt,
)
from .jwks import (
    HttpJwksProvider,
    JwksAuthenticator,
    JwksHttpSource,
    JwksProvider,
    StaticJwksProvider,
    UrllibJwksSource,
    jwk_from_public_numbers,
    verify_rs256,
)
from .audit import AuditEvent, AuditSink, InMemoryAuditLog, SqlAuditLog
from .apikeys import ApiKey, ApiKeyService, ApiKeyStore, InMemoryApiKeyStore, SqlApiKeyStore
from .openapi import API_VERSION, build_openapi
from .webhooks_out import (
    DeliveryResult,
    InMemoryWebhookEndpointStore,
    PlatformEvent,
    WebhookDispatcher,
    WebhookEndpoint,
    WebhookEndpointStore,
    briefing_sent_event,
    cash_at_risk_event,
    close_sealed_event,
    sign as sign_webhook,
)
from .invitations import (
    Invitation,
    InvitationError,
    InvitationService,
    InvitationStatus,
    InvitationStore,
    InMemoryInvitationStore,
    SqlInvitationStore,
)
from .rbac import (
    AccessPolicy,
    InMemoryUserDirectory,
    Membership,
    Permission,
    Role,
    SqlUserDirectory,
    User,
    UserDirectory,
    ROLE_PERMISSIONS,
    role_permissions,
)

__version__ = "0.1.0"

__all__ = [
    "WebApp",
    "Request",
    "Response",
    "serve",
    "make_handler",
    "wsgi_app",
    "request_from_environ",
    "RateLimiter",
    "ObservedApp",
    "security_headers",
    "with_security_headers",
    "default_rate_limit_key",
    "counter_request_ids",
    "render_login_html",
    "render_shell",
    "render_app_home",
    "render_users_admin",
    "render_transactions",
    "BankTransaction",
    "DEFAULT_CATEGORIES",
    "summarize",
    "render_cash_body",
    "render_briefing_body",
    "render_close_body",
    "render_packages_body",
    "CloseBoard",
    "CloseTask",
    "default_close_board",
    "TenantStore",
    "InMemoryTenantStore",
    "JsonFileTenantStore",
    "SqlTenantStore",
    "TenantState",
    "TenantDef",
    "FinancialPackageReader",
    "PackageIntegrityError",
    "canonicalize",
    "fingerprint_content",
    "verify_package",
    "render_package_html",
    "Authenticator",
    "StaticTokenAuthenticator",
    "JwtAuthenticator",
    "JwtError",
    "sign_jwt",
    "verify_jwt",
    "JwksAuthenticator",
    "JwksProvider",
    "StaticJwksProvider",
    "HttpJwksProvider",
    "JwksHttpSource",
    "UrllibJwksSource",
    "verify_rs256",
    "jwk_from_public_numbers",
    "AccessPolicy",
    "UserDirectory",
    "InMemoryUserDirectory",
    "SqlUserDirectory",
    "User",
    "Membership",
    "Role",
    "Permission",
    "ROLE_PERMISSIONS",
    "role_permissions",
    "AuditEvent",
    "AuditSink",
    "InMemoryAuditLog",
    "SqlAuditLog",
    "Invitation",
    "InvitationService",
    "InvitationStatus",
    "InvitationStore",
    "InMemoryInvitationStore",
    "InvitationError",
    "ApiKey",
    "ApiKeyService",
    "ApiKeyStore",
    "InMemoryApiKeyStore",
    "SqlApiKeyStore",
    "SqlInvitationStore",
    "build_openapi",
    "API_VERSION",
    "WebhookEndpoint",
    "WebhookEndpointStore",
    "InMemoryWebhookEndpointStore",
    "WebhookDispatcher",
    "PlatformEvent",
    "DeliveryResult",
    "sign_webhook",
    "cash_at_risk_event",
    "close_sealed_event",
    "briefing_sent_event",
]
